### ISSUE TITLE
Use case for Volunteer Toronto[VT User] - Drivers Application tab

### ISSUE THREAD

**Issue by swatiDgithub** [diglit/volunteer-toronto-volunteer-drivers-app#102]
# Description
https://xd.adobe.com/view/4a36317f-0fd9-444a-b1cd-e135d91ce2e0-1f65/screen/454aadfb-02ef-4b6e-9248-06eb55eca210?fullscreen&hints=off%5D

Use cases for the following designs:

Volunteer Toronto User Login 

~**Use case 1: Successful Login**~
~1.	User fills in the name field~
~2.	User fills in the password field~
~3.	User clicks the sign in button~
~4.	User arrives at dashboard~

**Use case 2: Review Application for Drivers by VT User  - Approve Scenario**
1.	VT User logs in with valid credentials. 
2.	User arrives on Dashboard with Volunteer Toronto Members tab in Focus
3.	User clicks on Drivers Application tab
4.	User clicks on Review Application in the first row 
5.	User reviews drivers pre-populated details 
6.	User clicks on Approve 
7.	User is prompted with a pop up with that confirms if he would like to approve the driver to the volunteer driver list 
8.	User clicks on the approve button on the pop up 
9.	User is navigated back to Drivers application tab 
10.	User clicks on Drivers Search Tab 
11.	User is able to see the approved Driver in the Driver Search. 

**Use case 3: Review Application for Drivers by VT User - Reject Scenario**
1.	VT User logs in with valid credentials
2.	User arrives on Dashboard with Volunteer Toronto Members tab in Focus
3.	User clicks on Drivers Application tab
4.	User clicks on Review Application in the first row
5.	User reviews drivers pre-populated details
6.	User clicks on Reject
7.	User is prompted with a pop up with that asks him to enter comments about why he wants to reject
8.	User enters comments
9.	User clicks on Reject button on the pop up
10.	User is navigated back to Drivers application tab
11.	User is not able to see the Rejected driver in the Drivers Application Tab

**Use case 4: Review Application for Drivers by VT User – Back Button Scenario**
1.	VT User logs in with valid credentials
2.	User arrives on Dashboard with Volunteer Toronto Members tab in Focus
3.	User clicks on Drivers Application tab
4.	User clicks on Review Application in the first row
5.	User reviews drivers pre-populated details
6.	User clicks on Back button
7.	User is Navigated Back to Drivers Application tab

# After Actions
Create cypress ticket(s) for these use cases. Use your judgement for the size.

<|<- META INFO (DO NOT MODIFY CONTENTS MANUALLY) ->|>
*BLOCKED BY*

- [x] #91,
- [ ] #103

*BLOCKING*

- [ ] #135

<|<- META INFO END ->|>

**Comment by l2silver** [comment]
Hey Swati

So I don't think we need the login section. (We'll cover that use case in the login work)

But other than that, this is perfect!
