### ISSUE TITLE
Write cypress tests for Use Case Ticket #102 - Volunteer Driver Applications tab.

### ISSUE THREAD

**Issue by swatiDgithub** [diglit/volunteer-toronto-volunteer-drivers-app#103]
# Description

Write cypress tests based on the following designs and use case issue

https://xd.adobe.com/view/4a36317f-0fd9-444a-b1cd-e135d91ce2e0-1f65/screen/454aadfb-02ef-4b6e-9248-06eb55eca210/?fullscreen&hints=off

Use Case Issue #102 

Dependencies: [Use Case Issue]

<|<- META INFO (DO NOT MODIFY CONTENTS MANUALLY) ->|>
*BLOCKED BY*

- [x] #130,
- [x] #131

*BLOCKING*

- [ ] #102

<|<- META INFO END ->|>

**Comment by l2silver** [comment]
This is perfect thanks!
