### ISSUE TITLE
Licencing the project as GPLv3

### ISSUE THREAD

**Issue by hkukreja** [diglit/volunteer-toronto-volunteer-drivers-app#146]
The current SAP Individual Contributor License Agreement has a few drawbacks. Here are a couple of them:

1. It grants SAP (and only SAP) the right to profit off our contributions
2. It exposes contributors to the jurisdiction of New York, USA

Licencing the project under the GNU General Public License v3.0 remedies these issues while simultaneously protecting the project against patent claims.

<|<- META INFO (DO NOT MODIFY CONTENTS MANUALLY) ->|>
*BLOCKED BY*

- [ ] #147,
- [ ] #147

*BLOCKING*

- [ ] #152

<|<- META INFO END ->|>

**Comment by l2silver** [comment]
@dnephin ^^

**Comment by dnephin** [comment]
Oh, ya that is weird. I think we selected the wrong agreement to show. I changed it from the SAP agreement to DCO-1.1 (created by the Linux Foundation),which you can see here: https://cla-assistant.io/diglit/volunteer-toronto-volunteer-drivers-app. That change may require people to sign the agreement again, unfortunately. The DCO-1.1 is much shorter, and it should basically just be an agreement that that contributor is only submitting work that they own or is licenses in a permissive way.

My understanding is that a contributor license agreement and the license applied to the software are slightly different things. The software license is for anyone using the software, the CLA is for anyone contributing to it.

 Adding a software license is very important as well. GPLv3 is probably a good choice for this project.
