### ISSUE TITLE
Create Drivers list

### ISSUE THREAD

**Issue by l2silver** [diglit/volunteer-toronto-volunteer-drivers-app#17]
# Description

Create the driver cards for the search page, as per specs and designs (https://xd.adobe.com/view/3b2fe38c-6d70-4a36-adab-e18285a668f0-6e7c/screen/9ec9e6d1-8442-49d2-98fd-44a0fbfe6137?fullscreen)

## Redux
The driver data will be stored in the redux store. Create a selector to grab the data. Refer to the readme for where to store the data.
```
{
  driversSearch: {
    drivers: Driver[]
  }
}

interface Driver {
  id: number,
  name: string,
  ...
}
```
# Acceptance Criteria

Client Organization Admin should see a list of drivers populated using the following mock data:
```
Driver[]
```

Lean heavily on material-ui for card

**Comment by dnephin** [comment]
Note that I changed some of the terminology in the description.

Is this the "search results page" ?

**Comment by WendyChenj** [comment]
> Note that I changed some of the terminology in the description.
> 
> Is this the "search results page" ?

Hi, Daniel. Thanks for your reminder. This is the Driver Card part on the search results page, excluding the filter.
