### ISSUE TITLE
Create Driver Registration - Remove save button

### ISSUE THREAD

**Issue by l2silver** [diglit/volunteer-toronto-volunteer-drivers-app#175]
Looks like a lot of the pages in driver registration include a save button. Lets remove the save button, and add that logic to the next button. So whenever someone clicks next, they move to the next slide, and save the data.

Reviewer: @ynynl 

<|<- META INFO (DO NOT MODIFY CONTENTS MANUALLY) ->|>
*BLOCKED BY*
No Issues

*BLOCKING*

- [ ] #22

<|<- META INFO END ->|>

**Comment by l2silver** [comment]
Reviewer: @mattchx

**Comment by ynynl** [comment]
I am working on #174 and found this might be helpful.
 https://stackoverflow.com/questions/60029351/how-to-validate-each-form-step-in-material-ui-stepper#63159346
