### ISSUE TITLE
Skeleton Create Org

### ISSUE THREAD

**Issue by l2silver** [diglit/volunteer-toronto-volunteer-drivers-app#206]
https://github.com/diglit/volunteer-toronto-volunteer-drivers-app#skeleton

Reviewer: @Haris188 

<|<- META INFO (DO NOT MODIFY CONTENTS MANUALLY) ->|>
*BLOCKED BY*

- [ ] #208

*BLOCKING*

- [ ] #209

<|<- META INFO END ->|>

**Comment by l2silver** [comment]
Hey @ynynl , do you mind completing this ticket first before you start working on development? It'll be easier to get other people involved once this ticket is complete. Thanks!

**Comment by ynynl** [comment]
> Hey @ynynl , do you mind completing this ticket first before you start working on development? It'll be easier to get other people involved once this ticket is complete. Thanks!

Sure!
