### ISSUE TITLE
Add more languages to language options

### ISSUE THREAD

**Issue by l2silver** [diglit/volunteer-toronto-volunteer-drivers-app#257]
{ name: 'english', label: 'English' },
        { name: 'french', label: 'French' },
        { name: 'tagalog', label: 'Tagalog' },
        { name: 'portuguese', label: 'Portuguess' },
        { name: 'spanish', label: 'Spanish' },
        { name: 'chinese', label: 'Chinese' },
        { name: 'other', label: 'Other' },

Add to the driver model

we need all of these languages. Try to use the 2 char code found here: https://www.sitepoint.com/iso-2-letter-language-codes/ . We can make other "ot"

**Comment by natastro** [comment]
Happy to provide Spanish translations if needed! 😊
