### ISSUE TITLE
Write API endpoint for returning search results

### ISSUE THREAD

**Issue by l2silver** [diglit/volunteer-toronto-volunteer-drivers-app#3]
# Description

Make sure the endpoint from #35  is searchable.

The search query can be for only a couple fields, don't worry about implementing everything right away.

# Acceptance Criteria

Search endpoint should exist, and should return an array of drivers that meet the search criteria, ordered by best fit to worst fit.

Request should look like:
```
{
  search_text: string,
  filter_1: any,
  ...
}
```

Response should look like:
```
{
  data: [
    {
      id: string|number,
      name: string,
      ...
    }
  ]
}
```

API structure should follow REST architecture. https://www.restapitutorial.com/

<|<- META INFO (DO NOT MODIFY CONTENTS MANUALLY) ->|>
*BLOCKED BY*

- [x] #149,
- [ ] #150

*BLOCKING*

- [ ] #154

<|<- META INFO END ->|>

**Comment by Erik-J-D** [comment]
@l2silver How committed are you to that request format? DRF can do query strings basically out of the box: https://www.django-rest-framework.org/api-guide/filtering/#searchfilter

**Comment by l2silver** [comment]
> @l2silver How committed are you to that request format? DRF can do query strings basically out of the box: https://www.django-rest-framework.org/api-guide/filtering/#searchfilter

@Erik-J-D Woh, this was from a long time ago. I think you're right, we should go with whatever works out of the box for django!
