### ISSUE TITLE
Create agreement section in signup flow

### ISSUE THREAD

**Issue by l2silver** [diglit/volunteer-toronto-volunteer-drivers-app#42]
# Description

Create the agrement section in signup flow: https://xd.adobe.com/view/3b2fe38c-6d70-4a36-adab-e18285a668f0-6e7c/screen/68b5ceac-c78c-4677-9e6f-df501a8b65ed

# Acceptance Criteria

Drivers needs to be able to select all options of agreement
Drivers needs to be able to fill in their name (as a signature)

# Additional Information

Make sure to talk to the other developers who are working on similar signup flow pages just to get a sense of what they're doing.

**Comment by ynynl** [comment]
@l2silver I am taking this ticket. How is the validation should look like?
