### ISSUE TITLE
Create e2e pretest for logging in

### ISSUE THREAD

**Issue by l2silver** [diglit/volunteer-toronto-volunteer-drivers-app#65]
# Description

Create a cypress pretest for logging in.

https://xd.adobe.com/view/3b2fe38c-6d70-4a36-adab-e18285a668f0-6e7c/

# Acceptance Criteria

Basic code should run and look for the raw elements with basic expectations.

# Domain information

Please refer to the README.md file in our e2e folder for best practices

<|<- META INFO (DO NOT MODIFY CONTENTS MANUALLY) ->|>
*BLOCKED BY*

- [x] #77

*BLOCKING*

- [ ] #153

<|<- META INFO END ->|>

**Comment by swatiDgithub** [comment]
Hi Leigh, Still working on this.. Was this moved to done by mistake ?

**Comment by l2silver** [comment]
Yep! I'll move it back, sorry about that!

**Comment by swatiDgithub** [comment]
Np!
